In [1]:
import numpy as np

In [3]:
ar1 = np.arange(12).reshape((4, 3))
ar1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
ar2 = np.arange(3)
ar2

array([0, 1, 2])

In [5]:
ar1 - ar2

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6],
       [9, 9, 9]])

In [6]:
np.dot(ar2, ar2)

5